/*
 * This file is generated by jOOQ.
*/
package com.eyesofkhepri.springbootjooqoauth2.generate;


import com.eyesofkhepri.springbootjooqoauth2.generate.tables.Author;
import com.eyesofkhepri.springbootjooqoauth2.generate.tables.Book;
import com.eyesofkhepri.springbootjooqoauth2.generate.tables.BookStore;
import com.eyesofkhepri.springbootjooqoauth2.generate.tables.BookToBookStore;
import com.eyesofkhepri.springbootjooqoauth2.generate.tables.Language;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in db_jooq
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>db_jooq.author</code>.
     */
    public static final Author AUTHOR = com.eyesofkhepri.springbootjooqoauth2.generate.tables.Author.AUTHOR;

    /**
     * The table <code>db_jooq.book</code>.
     */
    public static final Book BOOK = com.eyesofkhepri.springbootjooqoauth2.generate.tables.Book.BOOK;

    /**
     * The table <code>db_jooq.book_store</code>.
     */
    public static final BookStore BOOK_STORE = com.eyesofkhepri.springbootjooqoauth2.generate.tables.BookStore.BOOK_STORE;

    /**
     * The table <code>db_jooq.book_to_book_store</code>.
     */
    public static final BookToBookStore BOOK_TO_BOOK_STORE = com.eyesofkhepri.springbootjooqoauth2.generate.tables.BookToBookStore.BOOK_TO_BOOK_STORE;

    /**
     * The table <code>db_jooq.language</code>.
     */
    public static final Language LANGUAGE = com.eyesofkhepri.springbootjooqoauth2.generate.tables.Language.LANGUAGE;
}
