/*
 * This file is generated by jOOQ.
*/
package com.eyesofkhepri.generate;


import com.eyesofkhepri.generate.tables.Author;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in db_jooq
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>db_jooq.author</code>.
     */
    public static final Author AUTHOR = com.eyesofkhepri.generate.tables.Author.AUTHOR;
}
